## The purpose of these functions is to create an efficient method of obtaining
## the inverse of a matrix, when the matrix may or may not be updated when a program
## is being run.  Once the "cacheMatrix" vector is initialized the first time, for example
##    xCached <- cacheMatrix(x)
## then future updates to the matrix should be done using the xCached$set function
## cacheSolve(xCached) should then be used in place of solve(x) to obtain the inverse


## makeCacheMatrix creates a list of 4 functions to store or access a matrix, 
## or to store or access its inverse
makeCacheMatrix <- function(x = matrix()) {
    ## initialize the value of the matrix inverse to NULL
    inv <- NULL
    ## set function is used to update the matrix and NULL the previously cached inverse
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    ## get function is used to access the matrix cached in this function
    get <- function() x
    ## cache an inverse that has been computed
    setinv <- function(inverse) inv <<- inverse
    ## get the inverse currently cached (may be NULL)
    getinv <- function() inv
    ## return a list containing the 4 functions defined by this function
    list(set = set, get = get,
         setinv = setinv,
         getinv = getinv)
    
}


## cacheSolve operates on a "cached matrix" list generated by the function
## makeCacheMatrix.  It either returns the cached inverse or, if NULL is cached,
## computes the inverse and returns it
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    ## x must be an output of the function makeCacheMatrix
    ## if needed, replace ... with additional arguments for solve
    
    ## first check to see if the inverse has already been calculated
    ## if so, just return the inverse
    inv <- x$getinv()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    
    ##
    mat <- x$get()
    inv <- solve(mat, ...)
    x$setinv(inv)
    inv
    
}
